# Generated by Django 4.2 on 2023-10-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0004_apartment'),
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='condominiums.apartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='condominiums',
            field=models.ManyToManyField(blank=True, to='condominiums.condominium'),
        ),
    ]
