# Generated by Django 4.2 on 2023-10-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0004_apartment'),
        ('users', '0004_user_apartment_alter_user_condominiums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='condominiums.apartment'),
        ),
    ]
