# Generated by Django 4.2 on 2023-10-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_remove_apartment_renter'),
        ('users', '0006_alter_user_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='condominiums.apartment'),
        ),
    ]
