# Generated by Django 4.2 on 2023-10-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apartment',
        ),
    ]
