# Generated by Django 4.2 on 2023-10-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_apartment'),
    ]

    operations = [
    ]
