# Generated by Django 4.2 on 2023-12-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
