# Generated by Django 4.2 on 2023-10-04 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0003_alter_groupnotices_condominium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominiums.condominium')),
                ('renter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renter_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
