# Generated by Django 4.2 on 2023-10-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0004_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='renter',
        ),
    ]
