# Generated by Django 4.2 on 2023-10-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_remove_apartment_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='condominium',
        ),
    ]
