# Generated by Django 4.2 on 2023-10-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0007_delete_apartment'),
    ]

    operations = [
    ]
