# Generated by Django 4.2 on 2023-12-04 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0009_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='renter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
    ]
