# Generated by Django 4.2 on 2023-12-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0010_apartment_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aparment', to='condominiums.condominium'),
        ),
    ]
