# Generated by Django 4.2 on 2023-12-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0011_alter_apartment_condominium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='condominiums.condominium'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='condominium_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='condominium_name',
            field=models.CharField(max_length=100),
        ),
    ]
