# Generated by Django 4.2 on 2023-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0012_alter_apartment_condominium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominium',
            name='condominium_location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
