# Generated by Django 4.2 on 2023-12-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0013_alter_condominium_condominium_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='renter',
            new_name='renters',
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms_number',
            field=models.BigIntegerField(default=1),
        ),
    ]
