# Generated by Django 4.2 on 2023-12-12 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0014_rename_renter_apartment_renters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_condominium', to='condominiums.condominium'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renters',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renters', to=settings.AUTH_USER_MODEL),
        ),
    ]
