# Generated by Django 4.2 on 2024-01-12 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0017_alter_joiningrequest_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joiningrequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
