# Generated by Django 4.2 on 2024-01-12 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0018_alter_joiningrequest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joiningrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
