# Generated by Django 4.2 on 2024-01-12 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0020_rename_timestamp_joiningrequest_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joiningrequest',
            name='created_on',
        ),
        migrations.AddField(
            model_name='joiningrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
