# Generated by Django 4.2 on 2024-02-08 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0021_remove_joiningrequest_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privnotices',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='privnotices',
            name='sender',
        ),
        migrations.AddField(
            model_name='privnotices',
            name='apartment_resipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='condominiums.apartment'),
        ),
        migrations.AddField(
            model_name='privnotices',
            name='owner_sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('date', models.DateField()),
                ('recident_name', models.CharField(max_length=40)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expiry_date', models.DateField()),
                ('phone_number', models.IntegerField(blank=True, default=None, null=True)),
                ('apartment_receipt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_receipt', to='condominiums.apartment')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privnotices',
            name='rent_receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominiums.rentreceipt'),
        ),
    ]
