# Generated by Django 4.2 on 2024-02-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0022_remove_privnotices_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privnotices',
            name='image',
        ),
        migrations.RemoveField(
            model_name='privnotices',
            name='rent_receipt',
        ),
        migrations.CreateModel(
            name='PrivImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='media')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('apartment_receipt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_receipt_image', to='condominiums.apartment')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_owner_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
