# Generated by Django 4.2 on 2024-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0024_rename_apartment_resipient_privnotices_apartment_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privnotices',
            name='message',
            field=models.TextField(max_length=400),
        ),
    ]
