# Generated by Django 4.2 on 2024-02-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0025_alter_privnotices_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privnotices',
            name='message',
            field=models.CharField(max_length=400),
        ),
    ]
