# Generated by Django 4.2 on 2024-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0028_alter_rentreceipt_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privnotices',
            name='message',
            field=models.CharField(max_length=2000),
        ),
    ]
