# Generated by Django 4.2.4 on 2024-04-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0030_rentreceipt_total_amount_alter_rentreceipt_expenses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentreceipt',
            old_name='apartment_receipt',
            new_name='apartment_recipient',
        ),
    ]
