# Generated by Django 4.2.4 on 2024-04-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0031_rename_apartment_receipt_rentreceipt_apartment_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentreceipt',
            old_name='expiry_date',
            new_name='expire_date',
        ),
    ]
