# Generated by Django 4.2.4 on 2024-05-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condominiums', '0033_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='apartment_receipt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files_apartment', to='condominiums.apartment'),
        ),
        migrations.AddField(
            model_name='files',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
