# Generated by Django 4.2.4 on 2024-05-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0034_files_apartment_receipt_files_owner_files_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='apartment_receipt',
            new_name='apartment_recipient',
        ),
        migrations.RenameField(
            model_name='privimages',
            old_name='apartment_receipt',
            new_name='apartment_recipient',
        ),
    ]
