# Generated by Django 4.2.4 on 2024-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0035_rename_apartment_receipt_files_apartment_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privimages',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
    ]
