# Generated by Django 4.2.4 on 2024-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0036_privimages_title_alter_files_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='privimages',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
