# Generated by Django 4.2.4 on 2024-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0039_alter_files_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privimages',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='privimages',
            name='title',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
